name: Update README

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Find and update README
        run: |
          MOST_RECENT_FILE=$(ls -t consumed | head -n1)
          if [ -f "consumed/$MOST_RECENT_FILE" ]; then
            echo "## Content from $MOST_RECENT_FILE" >> README.md
            cat "consumed/$MOST_RECENT_FILE" >> README.md
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README with content from $MOST_RECENT_FILE"
            git push
          else
            echo "No file found in the consumed folder."
          fi
