name: Update README with Recent File

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find most recent file
        run: |
          # Ensure the 'consumed' directory exists and list files
          if [ -d "consumed" ]; then
            recent_file=$(ls -t consumed | head -n1)
            echo "Recent file: $recent_file"
            echo "recent_file=$recent_file" >> $GITHUB_ENV
          else
            echo "Directory 'consumed' does not exist."
            exit 1
          fi

      - name: Read and append the most recent file content to README.md
        run: |
          recent_file=${{ env.recent_file }}
          if [ -f "consumed/$recent_file" ]; then
            recent_file_content=$(cat "consumed/$recent_file")
            cat readme-default.md > README.md
            echo "$recent_file_content" >> README.md
          else
            echo "File 'consumed/$recent_file' does not exist."
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with recent file content" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CONSUMPTION_SECRET }}
