name: Update README

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Find and update README
        run: |
          TODAY=$(date +%u)
          if [ $TODAY -eq 1 ]; then
            RECENT_MONDAY=$(date +%m%d%y)
          else
            RECENT_MONDAY=$(date -d "last monday" +%m%d%y)
          fi
          FILE_TO_FIND=$RECENT_MONDAY.md
          if [ ! -f "$FILE_TO_FIND" ]; then
            FILE_TO_FIND=$(date -d "last month -$(date -d 'last monday' +%d) days" +%m%d%y).md
          fi
          if [ -f "$FILE_TO_FIND" ]; then
            echo "## Content from $FILE_TO_FIND" >> README.md
            cat "$FILE_TO_FIND" >> README.md
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README with content from $FILE_TO_FIND"
            git push
          else
            echo "No file matching the pattern found."
          fi
